[package]
name = "ic-timers-pocketic"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true

[dependencies]
candid.workspace = true
ic-testkit.workspace = true
serde = { workspace = true, features = ["derive"] }

[lints.rust]
unsafe_code = "forbid"
